'use client';

import { motion, Variants } from 'framer-motion';
import { Shield, Scale, FileText, ChevronRight, CreditCard } from 'lucide-react';
import Link from 'next/link';

const containerVariants: Variants = {
    hidden: { opacity: 0 },
    visible: {
        opacity: 1,
        transition: { staggerChildren: 0.1, delayChildren: 0.1 }
    }
};

const itemVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } }
};

export default function TermsPage() {
    const sections = [
        {
            title: "1. Dimensional Access",
            content: "By accessing the DraftRapid platform, you agree to bound by these terms. Our services are provided 'as is' and 'as available' for users operating within the legal limits of their jurisdiction."
        },
        {
            title: "2. Neural Intellectual Property",
            content: "All content generated by the Neural Forge remains the intellectual property of the user, provided that the subscription remains in good standing. DraftRapid retains the rights to the underlying algorithms and architectural blueprints."
        },
        {
            title: "3. Operational Gating",
            content: "Users are prohibited from using the platform for malicious purposes, including but not limited to the generation of misinformation, harassment, or unauthorized system penetration."
        },
        {
            title: "4. Termination Protocols",
            content: "DraftRapid reserves the right to terminate access to the matrix at any time should a breach of operational protocols be detected. All data may be purged upon termination."
        },
        {
            title: "5. Payment Processing & Merchant of Record",
            content: "Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle provides all customer service inquiries and handles returns. By completing a purchase on DraftRapid, you agree to Paddle's terms of service and privacy policy in addition to these Terms. For billing questions, refunds, or payment disputes, please contact support@draftrapid.app or refer to our Refund Policy."
        }
    ];

    return (
        <div className="min-h-screen bg-[#050505] text-white selection:bg-primary/30 relative overflow-hidden font-sans pt-32 pb-20">
            {/* Cinematic Background Artifacts */}
            <div className="absolute top-0 right-0 w-[800px] h-[600px] bg-primary/5 blur-[150px] pointer-events-none rounded-full" />

            <div className="max-w-4xl mx-auto px-6 relative z-10">
                <motion.div
                    variants={containerVariants}
                    initial="hidden"
                    animate="visible"
                    className="space-y-12"
                >
                    {/* Header */}
                    <header className="text-center mb-16">
                        <motion.div variants={itemVariants} className="inline-flex items-center gap-3 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full mb-6">
                            <Shield className="h-4 w-4 text-primary" />
                            <span className="text-[10px] font-black tracking-[0.3em] uppercase text-primary">Protocol documentation</span>
                        </motion.div>
                        <motion.h1 variants={itemVariants} className="text-5xl md:text-7xl font-black tracking-tighter uppercase leading-none">
                            TERMS OF <span className="text-gradient">SERVICE</span>
                        </motion.h1>
                        <motion.p variants={itemVariants} className="text-white/30 mt-6 font-bold tracking-widest uppercase text-xs">
                            Last Updated: February 21, 2026
                        </motion.p>
                    </header>

                    {/* Structured Content */}
                    <div className="space-y-6">
                        {sections.map((section, i) => (
                            <motion.div key={i} variants={itemVariants} className="glass-card p-10 rounded-[2.5rem] border-white/5 relative group">
                                <div className="flex items-start gap-6">
                                    <div className="w-12 h-12 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-center shrink-0">
                                        {i === 4 ? <CreditCard className="h-5 w-5 text-primary" /> : <Scale className="h-5 w-5 text-primary" />}
                                    </div>
                                    <div>
                                        <h2 className="text-xl font-black tracking-widest uppercase mb-4 text-white group-hover:text-primary transition-colors">
                                            {section.title}
                                        </h2>
                                        <p className="text-white/40 leading-relaxed font-medium">
                                            {section.content}
                                        </p>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>

                    {/* Policy Overview Card */}
                    <motion.div variants={itemVariants} className="p-8 bg-white/[0.02] border border-white/5 rounded-3xl">
                        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                            <div className="flex items-center gap-4">
                                <FileText className="h-6 w-6 text-primary" />
                                <span className="text-sm font-bold text-white/50 leading-tight">
                                    For more detailed information regarding data handling, please consult our Privacy Policy.
                                </span>
                            </div>
                            <div className="flex flex-wrap gap-4">
                                <Link href="/privacy" className="flex items-center gap-2 text-[10px] font-black tracking-[0.2em] uppercase text-primary hover:text-white transition-colors whitespace-nowrap">
                                    Privacy Policy <ChevronRight className="h-4 w-4" />
                                </Link>
                                <Link href="/refund" className="flex items-center gap-2 text-[10px] font-black tracking-[0.2em] uppercase text-primary hover:text-white transition-colors whitespace-nowrap">
                                    Refund Policy <ChevronRight className="h-4 w-4" />
                                </Link>
                            </div>
                        </div>
                    </motion.div>

                    {/* Footer Navigation Link */}
                    <motion.div variants={itemVariants} className="text-center pt-10">
                        <Link href="/" className="text-white/20 hover:text-white transition-colors text-xs font-black tracking-[0.3em] uppercase">
                            ← Return to Matrix
                        </Link>
                    </motion.div>
                </motion.div>
            </div>
        </div>
    );
}
